### ISSUE TITLE
Profile selection doesn't work

### ISSUE THREAD

**Issue by wouterdebie** [wouterdebie/i2cssh#117]
@damientkk reported:

The profile option with -p appears to be broken. Using the
following syntax "i2cssh -b -p Prod -XA -XY -c clusterA", the Prod profile
for the windows (e.g Green background) shows up briefly before resetting to
the default terminal settings when connections to the various hosts have
been established. Any idea why that might be the case?

**Comment by damientkk** [comment]
Hi Wouter,

Sorry I missed your message. The issue is due to the setting "Prevent
control sequences from changing the current profile" I have on iTerm2
Advanced tab, it's currently set to "No" on my end. Instead of using
Automatic Profile Switching, I have a shell script/function to change my
Profile depending on the host I am sshing to using "echo -e
"\033]50;SetProfile=<Profile>\a". Somehow, when calling i2cssh, the profile
I specify e.g Green background is overwritten by something else. This is
evident from the initial launch of sessions with Green background, only to
change to white background after some additional code run. This behaviour
is not happening in the older version of i2cssh/iTerm2.

In the meantime, my workaround is to change the value of "Prevent control
sequences from changing the current profile" to Yes when I need to invoke
i2cssh.

Thanks,
Damien

**Comment by wouterdebie** [comment]
Thanks for the explanation. It's interesting behavior for sure. The old version of i2cssh basically mimicked key strokes with Applescript to split panes, which was kind of wonky, where the new version uses the python API provided by iterm2. The old way of setting the profile was exactly as you do in a script by echoing some escape codes, but the new way is to use the `async_split_pane()` function the API provides. This function takes a profile name as argument, so i2cssh doesn't do anything special or crazy. 

It's interesting that the two don't seem to play nicely. And I can't seem to reproduce it manually though. If I start an i2cssh session with a profile (say p1) and then I do `echo -e "\033]50;SetProfile=p2\a"` it nicely switches to the p2 profile.

**Comment by damientkk** [comment]
Can you let me know what is the value you have for "Prevent control
sequences from changing the current profile" in the Advanced Tab -->
Terminal? And are you using Shell integration? Maybe I have some other
settings that might be at play here :)

**Comment by wouterdebie** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/172038/218778658-3cd8e9ac-a904-48d8-9acb-87bc338b0e74.png">

**Comment by wouterdebie** [comment]
@damientkk any updates here?

**Comment by wouterdebie** [comment]
Closing this issue since It's been open for a while.
