### ISSUE TITLE
FEATURE REQUEST: Allow custom commands

### ISSUE THREAD

**Issue by joelsdc** [wouterdebie/i2cssh#118]
**Describe the new feature**
Add an option to allow running custom commands instead of only ssh.

**Additional context**
I know this might be outside of the scope of i2cssh by the nature of its name, but you can't imagine how much I use i2cssh, and how happy I am that you decided to rewrite it in Python as now I can understand the code and maybe even collaborate.

Use-case:

Any command you wish to run in multiple windows but not ssh related. For me, this is especially useful when interacting with kubernetes via `kubectl`.

For example, I find myself in situations where I need to troubleshoot something specific and I have to check the logs of multiple pods in k8s at the same time.

If I have in my i2cssh yaml file something like:

```yaml
---
version: 2
clusters:
    deploymentX:
        hosts:
            - pod1
            - pod2
            - pod3
            - pod4
```

It would be amazing if I could do something along:

`i2cssh deploymentX -z "kubectl logs -f ${I2CSSH_HOST} --tail=10"`

NOTE: `-z` is an example to specify a custom command and `${I2CSSH_HOST}` would be a placeholder replaced with the actual value from the yaml file.

And i2cssh would open a new window with 4 tabs, each with:

```
kubectl logs -f pod1 --tail=10
kubectl logs -f pod2 --tail=10
kubectl logs -f pod3 --tail=10
kubectl logs -f pod4 --tail=10
```

Thank you in advance!

**Comment by wouterdebie** [comment]
@joelsdc First of all thank you for the kind words! I'm happy you use i2cssh often! Since I thought that this feature request was great and it was very simple to implement, I went ahead and did it. You can find the functionality added in 0.0.14. Note that the option is `-x` or `--custom-command` or `custom_command` (in config) instead of your proposed `-z`. Also, I wanted to stay away from `$` stuff, since that might lead to shell substitutions, so I chose `{host}` as the substitution string. This also allows for other substitutions in the future if we ever need them.

Let me know if this works for you and I'll close this issue.

**Comment by joelsdc** [comment]
Hi @wouterdebie:

The `-z` and `${I2CSSH_HOST}` were only examples for me to explain to you the feature request, I totally agree with your approach.

I've tested this and it works perfectly. I'm so thankful to you for implementing this, and double thankful for doing it so fast. 

Really appreciate it 👍 👍 👍
