### ISSUE TITLE
Question: can new windows inherit env vars of source window?

### ISSUE THREAD

**Issue by ppi-agray** [wouterdebie/i2cssh#143]
When I run `i2cssh -m i-0522b3e10e176a090`, I would like the target window to inherit the env vars of where I called it.

The reason being I have AWS access and secret keys that allow me to ssh onto instance IDs, not IP addresses.

But the target window doesn't have those env vars, and thus fails.

It would be awesome if the target window inherits the env vars from the terminal that launched it.

Thanks!

**Comment by wouterdebie** [comment]
Sorry for the incredible late reply, but for some reason I never got the notification for this issue. 

Anyway. Right now, the shell in the new window is spawned using `/usr/bin/env <SHELL> -l`, where SHELL defaults to bash. The `-l` should give it a login shell, which means that your .bashrc and such should be read. If you use another shell (e.g. zsh) you can run with `-S` (or equivalent `shell` in config) to change the shell that starts.

MacOS changed from bash to zsh as the default shell a while back, so I might change this behavior. I think what I'll do is to rely on the `$SHELL` env var instead of assuming the shell unless `-S` is specified.

**Comment by wouterdebie** [comment]
This should be fixed in 0.2.0. Let me know if this helps.
