### ISSUE TITLE
gem outdated

### ISSUE THREAD

**Issue by spawnflagger** [wouterdebie/i2cssh#99]
Hello, on Catalina default shell is zsh, and I noticed this bug: #98 , but the i2cssh (2.2.0) which I just installed doesn't have the `--shell` or `-S` option.
I checked on [rubygems](https://rubygems.org/gems/i2cssh), and 2.2.0 is from 2016, but the shell option was added in 2017.

I did a diff of _bin/i2cssh_ and _lib/i2cssh.rb_ from a git clone and the installed (/Library/Ruby/Gems/2.6.0/gems/i2cssh-2.2.0/, and the only differences are related to adding the shell option. 

(I assume there's a way to install the Gem from the git clone directory, I'm just not familiar with Ruby best practices)

Lastly, should probably update the README.md to include the shell option as well...

**Comment by Schokobecher** [comment]
Late to the party, but this can be fixed by:


- Clone the Git
- Editing _lib/i2cssh.rb_ (change _bash_ to _zsh_
- Running `gem build i2cssh.gemspec` (this builds the gem file)
- Running `sudo gem install i2cssh-2.2.0.gem` which installs the updated gem

It seems @wouterdebie doesn't maintain this project anymore. Maybe someone can step in and help out?

**Comment by wouterdebie** [comment]
I just moved to a python version. This should solve a bunch of issues. Please check it out.
